import bcrypt from 'bcryptjs';

const data = {
  users:[
    {
      name:'Talha',
      email:'talha1503@gmail.com',
      password: bcrypt.hashSync('1234',8),
      isAdmin:true,
    },
    {
      name:'john',
      email:'talha15032@gmail.com',
      password: bcrypt.hashSync('1234',8),
      isAdmin:false,
    },
  ],
  products: [
    {
      name: 'Nike Slim Shirt',
      category: 'Shirts',
      image: '/images/p1.jpg',
      countInStock: 10,
      price: 120,
      brand: 'Nike',
      rating: 1,
      numReviews: 10,
      description: 'high quality product',
    },
    {
      name: 'Adidas Fit Shirt',
      category: 'Shirts',
      image: '/images/p2.jpg',
      countInStock: 20,
      price: 100,
      brand: 'Adidas',
      rating: 2,
      numReviews: 10,
      description: 'high quality product',
    },
    {
      name: 'Lacoste Free Shirt',
      category: 'Shirts',
      image: '/images/p3.jpg',
      countInStock: 0,
      price: 220,
      brand: 'Lacoste',
      rating: 3,
      numReviews: 17,
      description: 'high quality product',
    },
    {
      name: 'Nike Slim Pant',
      category: 'Pants',
      image: '/images/p4.jpg',
      countInStock: 15,
      price: 78,
      brand: 'Nike',
      rating: 4.5,
      numReviews: 14,
      description: 'high quality product',
    },
    {
      name: 'Puma Slim Pant',
      category: 'Pants',
      image: '/images/p5.jpg',
      countInStock: 5,
      price: 65,
      brand: 'Puma',
      rating: 4.5,
      numReviews: 10,
      description: 'high quality product',
    },
    {
      name: 'Adidas Fit Pant',
      category: 'Pants',
      image: '/images/p6.jpg',
      countInStock: 12,
      price: 139,
      brand: 'Adidas',
      rating: 4.5,
      numReviews: 15,
      description: 'high quality product',
    },
  ],
};
export default data;
